### ISSUE TITLE
Potential Undefined Behavior in from_executable Due to Unsafe Pointer Usage and Assumptions

### ISSUE THREAD

**Issue by lwz23** [m4b/dryad#6]
**Description**
The from_executable function contains unsound code that can lead to undefined behavior (UB) due to unsafe pointer dereferencing and assumptions about external inputs (e.g., phdr_addr, phnum, and lachesis). These issues compromise the memory safety guarantees expected from Rust.
https://github.com/m4b/dryad/blob/db1dd3c2712dafd28788b4cdafec09c0312a8db0/src/image.rs#L149
```
pub fn from_executable (name: &'static str, phdr_addr: usize, phnum: usize, lachesis: &mut tls::Lachesis) -> Result<SharedObject<'process>, String> {
    unsafe {
        let addr = phdr_addr as *const ProgramHeader;
        let phdrs = ProgramHeader::from_raw_parts(addr, phnum);
        ...
    }
}
```
**Problems:**
Unsafe Pointer Casting and Dereferencing:

The function casts phdr_addr (a usize) to *const ProgramHeader and passes it to ProgramHeader::from_raw_parts.
If phdr_addr is not a valid pointer or does not align with ProgramHeader, the program may invoke undefined behavior.
Assumption of Valid Memory:

ProgramHeader::from_raw_parts(addr, phnum) assumes that the range [addr, addr + phnum * size_of::<ProgramHeader>()] is valid and accessible. If this assumption is violated (e.g., phnum is too large or addr points to invalid memory), UB will occur.
Unchecked Arithmetic:

Expressions like phdr_addr - phdr.p_vaddr as usize and (link_info.strtab - link_info.symtab) / link_info.syment may cause overflow or invalid computations, leading to incorrect behavior or UB.
Dynamic Table Assumptions:

The function assumes that link_info.strtab, link_info.symtab, and other dynamic table pointers are valid. If they are incorrect or misaligned, subsequent operations like sym::from_raw or Strtab::from_raw will result in UB.
Use of Raw Pointers Without Validation:

The function directly constructs raw pointers like link_info.symtab as *const sym::Sym and performs unchecked operations. If these pointers are invalid or point to incorrect memory, UB will occur.
Unclear Lifetimes:

The returned SharedObject contains references to memory derived from raw pointers, but there is no guarantee that this memory will remain valid for the lifetime of the object.
Panics Instead of Proper Error Handling:

The line link_info.pltgot.expect("Error executable has no pltgot, aborting") panics instead of returning an error. This is not a memory safety issue but can lead to unpredictable application behavior.

**Steps to Reproduce:**
Here is an example of how these issues might arise:
```
let invalid_phdr_addr = 0xdeadbeefusize; // Invalid address
let invalid_phnum = usize::MAX;          // Unrealistic number of program headers

let result = from_executable(
    "test_exec",
    invalid_phdr_addr,
    invalid_phnum,
    &mut tls::Lachesis::new(),
);

assert!(result.is_err()); // Undefined behavior may occur before reaching this point

```
**Expected Behavior:**
The function should:
Validate that phdr_addr and phnum point to valid and properly aligned memory.
Ensure that the DynamicInfo fields and pointers are valid before dereferencing them.
Handle errors robustly instead of panicking.
**Additional Context:**
Unsafe code blocks in Rust are highly error-prone and should be thoroughly reviewed to ensure all safety invariants are upheld. Misuse of raw pointers can lead to memory corruption, crashes, or security vulnerabilities.

**Comment by koutheir** [comment]
I assume pull requests are welcome in this project, maybe some AI chat bot can write that too...

**Comment by m4b** [comment]
The future is going to be filled with crap and mindless slop.

Not sure why I’m responding to what is obviously a bot but the unsafe methods rely in part on the executable being verified by the kernel. Additionally this was an experiment, to see how suitable rust could be for a project like this, and also to teach myself rust at a lower level, and written many years ago so yes there are probably some sharp edges or unsound entry points.

I still remember inline asm being added to nightly and not having to compile and link some separate asm, and that was nice ! It probably won’t even compile anymore :)

anyway, memories …
